version: '3.3'
services:
  db:
    build: ./Database
    ports:
      - "3306:3306"
    networks:
            overlay:
    environment:
            MYSQL_ROOT_PASSWORD: password      
  web:
    build: ./Web/webphp
    ports:
      - "8080:80"
    networks:
            overlay:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 20M
        reservations:
          cpus: '0.05'
          memory: 10M

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
            overlay:

  elasticsearch:
    image: elastic/elasticsearch:6.4.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
        #expose:
        # - 9200
    ports:
      - "9200:9200"
    networks:
            overlay:

  kibana:
    image: elastic/kibana:6.4.3
    ports:
      - "5601:5601"
    networks:
            overlay:
                    
networks:
        overlay:                   
