- hosts: master
  become: yes
  become_method: sudo
  tasks:
          - name: docker swarm init
            shell:  docker swarm init --advertise-addr 192.168.56.110 > token.txt

- hosts: worker_1 worker_2 worker_3
  become: yes
  tasks:
          - name: copiar archivo
            shell: scp master@192.168.56.110 /home/token.txt

          - name: join
            shell: docker swarm join --token $(cat token.txt | grep "\--token" | awk '{print $2}') 192.168.53.110:2377

#name
