- hosts: master
  become: yes
  become_method: sudo
  tasks:
          - name: docker swarm init
            shell:  docker swarm init --advertise-addr 192.168.56.110
            ignore_errors: yes
          - name: hola
            shell: docker swarm join-token -q worker > /home/vagrant/token.txt

          - name: change token permissions
            shell:  chmod 777 /home/vagrant/token.txt
            ignore_errors: yes
          
          - name: deshabilitar firewalld
            shell: systemctl stop firewalld


