- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors CRI --apiserver-advertise-address $(hostname -I | awk '{print $2}')  --ignore-preflight-errors=SystemVerification
    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
    - name: get master ip raw variable
      shell: echo $(hostname -I | awk '{print $2}')
      register: ip_raw
    - name: set ip variable
      set_fact:
        ip: "{{ ip_raw.stdout_lines[0] }}"
    - name: Init docker swarm cluster
      shell: docker swarm init --advertise-addr {{ip}}
