---


        
          
- hosts: master
  become: yes
  tasks:
          - name: gluster add node1
            shell:
                    cmd: gluster peer probe 192.168.56.111
          - name: gluster add node2
            shell:
                    cmd: gluster peer probe 192.168.56.112
            ignore_errors: yes
          - name: gluster add node3
            shell:
                    cmd: gluster peer probe 192.168.56.113
          - name: create volume
            shell:
                    cmd: gluster volume create swarm-vols replica 4 192.168.56.110:/gluster/data 192.168.56.111:/gluster/data 192.168.56.112:/gluster/data 192.168.56.113:/gluster/data force     
            ignore_errors: yes
          
          - name: gluster start volume
            shell:
                    cmd: gluster volume start swarm-vols
            ignore_errors: yes
- hosts: all
  become: yes
  tasks:
          - name: mount swarm in all nodes
            shell:
                    cmd: mount.glusterfs localhost:/swarm-vols /swarm/volumes
            ignore_errors: yes
                     
