- hosts: master
  become: yes
  tasks:
    - name: Add EPEL YUM repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    - name: Install the packages for python-pip
      yum: 
        name:  python-pip 
        state: present
        disable_gpg_check: true
    - name: Install the latest docker-compose package
      pip: name=docker-compose state=latest
    - name: Copy docker-compose folder
      copy:
        src: ../docker-compose
        dest: /
        mode: 0774
    - name: build containers
      command: docker-compose build
      args:
        chdir: /docker-compose/
    - name: execute containers
      command: docker-compose up
      args:
        chdir: /docker-compose/