version: '3'
services:
  aplicacion:
            build: ./aplicacion
            image: aplicacion:1.0
            ports:
             - "5000:5000"
            volumes:
             - ../aplicacion:/code
            deploy:
              resources:
                limits:
                  cpus: '0.10'
                  memory: 20M
                reservations:
                  cpus: '0.05'
                  memory: 10M

